### ISSUE TITLE
opensea kakao link로 변경

### ISSUE THREAD

**Issue by gimdongwon** [gimdongwon/kangnamlion#1]
### jira

- DT-

### history

- ?

### schedule

- ?

### todo

- [x] 카카오 링크로 옮길 항목 정리
- [x] 카카오 링크 템플릿 생성
- [x] 카카오 링크 템플릿에 맞춘 값 생성 및 연동
- [x] Klay값 추가
- [x] Klay로 이더값 연산

### information

- ?

### cc

- @gimdongwon @seunggabi
