### ISSUE TITLE
[discussion] CI/CD 논의

### ISSUE THREAD

**Issue by seunggabi** [gimdongwon/kangnamlion#16]
### history

- #2 
- #15 

### schedule

- ?

### todo

- [x] #12 
- [ ] `/sdcard/msgbot/kangnamlion` -> `/sdcard/kangnamlion`
  - [ ] clone
  - [ ] pull `git config credential.helper store --global`
  - [ ] 코드 버저닝 `git-pull.sh` 
- [ ] #9 (@seunggabi )

### information

- ?

### cc

- @gimdongwon @seunggabi
