### ISSUE TITLE
에러처리

### ISSUE THREAD

**Issue by gimdongwon** [gimdongwon/kangnamlion#25]
### history

- 정말 많은 에러처리 경우가 많다. 기능 위주로 개발을 하다보니 에러처리가 많이 안되엇는데 하나하나 적어가면서 해결해보자.

### schedule

- ?

### todo

- [x] 코로나로 시작하는 말이면 명령어 동작함 ex) "코로나도 심하고"
- [x] 사전추가 에러처리 ex) "사전추가 하십쇼" 빈칸이 사전추가 됨.
- [x] 서버가 갑자기 죽음. 근데 제현이 안됨. 빗썸, 주식 함수들. 명령어로 원격으로 restart하는 기능 시급.
- [x] ex) 주식 루닛. 내용이 없을시 에러 코드 그대로 표현됨. 사용자 친화적으로 변경할 것.
- [x] ex) 날씨 미쳤네. 검색햇을때 검색에러 잇으면 아무처리 하지않도록 변경.
- [x] 사전추가시 빈칸 추가될 시 아무처리하지 않도록 변경.
- [x] 코로나 없는 나라 검색시 아무처리하지 않도록 변경.
- [ ] 오픈씨 가격 정확히 안맞음

### information

- 에러처리가 해결되야 서비스의 완성도가 올라간다. 천천히 하나하나 잘 생각하며 처리해보자.
- 어떤 방식으로 명령어를 입력받을지 적어보자. 
    - 일단 " "을 기준으로 나눈 첫 항목이 해당 명령어이면 반응하고 뒤에 지침 내용이 하나일경우 리스트에서 확인하고 2개면 둘다 정확히 잇는지 확인하는방법.

### cc

- @gimdongwon @seunggabi
